### ISSUE TITLE
WinUI Enhancements

### ISSUE THREAD

**Issue by MadEste** [dotnet/try-convert#308]
# WinUI3 Conversion To Do
This is specific to the feature/winui branch. #306
There are still some requirements and improvements for a UWP App to WinUI3 Conversion feature.
- [ ] UWP => Desktop, .wapproj should be configured to use .csproj as app entry point.
- [ ] UWP => Desktop, old appxmanifest should use .wapproj and change entry point to FullTrustApplication.
- [ ] Microsoft.CodeAnalysis.MSBuild.MSBuildWorkspace does not support new documents.
    - [ObservableCollection](https://github.com/microsoft/microsoft-ui-xaml/issues/1557) Codefix depends on adding a new document/class to the solution. Currently disabled since the workspace does not support adding/removing documents. [StackOverflow](https://stackoverflow.com/questions/36135604/how-add-existing-project-to-c-sharp-solution-with-roslyn?rq=1), [Documentation](https://docs.microsoft.com/en-us/dotnet/api/microsoft.codeanalysis.workspace.applyadditionaldocumentadded?view=roslyn-dotnet#Microsoft_CodeAnalysis_Workspace_ApplyAdditionalDocumentAdded_Microsoft_CodeAnalysis_DocumentInfo_Microsoft_CodeAnalysis_Text_SourceText_)
- [ ] Application.OnLaunched Method needs to start window in a frame, Some UWP apps still use [`Window.Current`](https://github.com/microsoft/microsoft-ui-xaml/issues/2609) which returns null in WinUI3. Create an Analyzer/CodeFix to update the C# source code?
- [ ] Analyzers/Codfixes are slow. Implement batch fixer or [edit multiple documents.](https://github.com/dotnet/roslyn/issues/40598)
- [ ] MultiTargeting Library .csproj converts properly but cannot be built. These are not errors with try-convert but WinUI3 and the WindowsCommunityToolkit.
- [ ] Sometimes nuget.targets breaks try-convert #124 . Emit a better error message?
- [ ] Roslyn Analyzers cannot parse .xaml files. Implement xml reader or find/replace to update to [webview2](https://docs.microsoft.com/en-us/microsoft-edge/webview2/gettingstarted/winui)?
- [ ] Cpp Source Code cannot be converted.

**Comment by cartermp** [comment]
Thanks @MadEste!

**Comment by stevenbrix** [comment]
> Roslyn Analyzers cannot parse .xaml files. Implement xml reader or find/replace to update to webview2?

@mrlacey for FYI on consuming the RapidXaml analyzers, which he demoed the WebView2 converter during the last community call

There are also some changes to IXP APIs that have been moved the `.Experimental` namespaces and are all prefixed with `Exp`. Depending on the timeline of this tool, we may want to update analyzer+code fixers to make these changes.

**Comment by mrlacey** [comment]
I have a PoC for converting `WebView` to `WebView2` that also takes care of adding/using appropriate xmlns. This is at https://github.com/mrlacey/TryConvertXaml/blob/main/TryConvertXamlSample/Program.cs

It's based on functionality from https://aka.ms/rxt 

I just need to remove the final dependency on the VisualStudio SDK (it was originally solely a VSIX) and then can have it target .NET Standard. Due to the uncertainty of a timeline for this it wasn't previously a priority, but working on this again now.

**Comment by stevenbrix** [comment]
>Due to the uncertainty of a timeline for this it wasn't previously a priority, but working on this again now.

@mrlacey my apologies if I gave a pretense that we were looking into the xaml analyzers soon. There is still no real certain timeline yet, so please don't feel rushed. After Preview3 we could look into this, but then it's the holiday season, so it's a real possibility this won't be picked up until the new year.

**Comment by mrlacey** [comment]
> > Due to the uncertainty of a timeline for this it wasn't previously a priority, but working on this again now.
> 
> @mrlacey my apologies if I gave a pretense that we were looking into the xaml analyzers soon. There is still no real certain timeline yet, so please don't feel rushed. After Preview3 we could look into this, but then it's the holiday season, so it's a real possibility this won't be picked up until the new year.

Ok. Just wanted to get the current limitation documented and note that I was working on it. Just bumping it up my own internal backlog as it has other benefits for me too. I want to make sure it is done before it's needed here.

**Comment by stevenbrix** [comment]
Also this just came to mind, is how do we convert .csproj which are using a C++ runtime component. you now need to create an interop project in most cases, and it's a non-trivial amount of work to do so

/cc @angelazhangmsft

**Comment by Marv51** [comment]
Is there a build of the WinUI branch available or should I build from source?

**Comment by mrlacey** [comment]
If and when this gets picked up again, I have an [improved version of my library](https://www.nuget.org/packages/RapidXaml.AutoFix/1.0.5) that can be used for the XAML changes.
It's improved on the basis that this version:
- is much smaller
- has fewer dependencies
- is now netStandard2.0 (so can be used **anywhere**)
